name: verify commits

on:
  push:
    paths:
      - '**.py'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: flake8
      run: |
        flake8 --count --show-source --statistics *.py visualvocab
    - name: isort
      run: |
        isort -c *.py visualvocab
    - name: mypy
      run: |
        mypy *.py visualvocab
    - name: pytest
      run: |
        pytest tests
